name: Build PC Shadows

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r25c
      - name: Build
        run: |
          ${{ steps.ndk.outputs.ndk-path }}/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./jni/Android.mk NDK_APPLICATION_MK=./jni/Application.mk -j$(nproc)
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libshadowpc-arm32
          path: libs/armeabi-v7a/libshadowpc.so
